using '../main.bicep'

param fabricCapacityName = 'fabricagentdemo'
param keyVaultName = 'fsa-agent-kv-2026'
param entraAppName = 'FSA-WorkIQ-Agent'
param fabricCapacitySku = 'F2'
param fabricAdminUpn = 'admin@MngEnvMCAP529863.onmicrosoft.com'
param storageAccountName = 'fsaagentstorage2026'
param cogServicesName = 'fabricagentai2026'
param foundryHubCogServicesName = 'fsa-hub-2026'
param foundryHubName = 'fabric-agent-hub'
param foundryProjectName = 'fsa-project'
