using '../main.bicep'

param fabricCapacityName = 'fabricagentdemodev'
param keyVaultName = 'fsa-agent-kv-dev-2026'
param entraAppName = 'FSA-WorkIQ-Agent-Dev'
param fabricCapacitySku = 'F2'
param fabricAdminUpn = 'admin@MngEnvMCAP529863.onmicrosoft.com'
param storageAccountName = 'fsaagentstorage2026d'
param cogServicesName = 'fabricagentaidev2026'
param foundryHubCogServicesName = 'fsa-hub-dev-2026'
param foundryHubName = 'fabric-agent-hub-dev'
param publicNetworkAccess = 'Enabled'
param foundryHubStorageRoleAssignmentName = 'c52d7250-ea78-4536-b15a-d45b2bad6c97'
