"""Report Generator — converts structured data + templates into DOCX and PPTX with full citations."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Any, TypedDict, cast

import matplotlib
from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt
from pptx import Presentation
from pptx.slide import Slide
from pptx.util import Emu
from pptx.util import Inches as PptxInches
from pptx.util import Pt as PptxPt

matplotlib.use("Agg")

from matplotlib import pyplot as plt  # noqa: E402
from matplotlib.ticker import FuncFormatter  # noqa: E402

_FOOTER_TEXT = "Generated by Fabric Sales Agent Accelerator"
_TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"
_DEFAULT_DOCX_TEMPLATE = "account_plan.md"


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


class PipelineRow(TypedDict, total=False):
    deal_name: str
    value: float
    stage: str
    close_date: str
    customer: str


class ResearchArticle(TypedDict, total=False):
    title: str
    source: str
    url: str
    snippet: str
    summary: str
    date: str


class ResearchData(TypedDict, total=False):
    company_name: str
    summary: str
    articles: list[ResearchArticle]


class SharePointDoc(TypedDict, total=False):
    name: str
    url: str
    excerpt: str


@dataclass
class ForecastItem:
    """Single product category forecast."""

    category: str
    current_fy_revenue: float
    growth_rate: float
    projected_fy_revenue: float


@dataclass
class ForecastData:
    """FY quota forecast data."""

    customer_name: str
    current_fy_total: float
    projected_fy_total: float
    overall_growth_rate: float
    methodology: str
    items: list[ForecastItem] = field(default_factory=list)


@dataclass
class ReportData:
    """Structured payload consumed by the report generators."""

    title: str
    customer_name: str
    generated_at: datetime
    pipeline_data: list[PipelineRow] = field(default_factory=list)
    research_data: ResearchData = field(default_factory=lambda: cast(ResearchData, {}))
    sharepoint_docs: list[SharePointDoc] = field(default_factory=list)
    additional_context: str | None = None
    forecast_data: ForecastData | None = None


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _fmt_timestamp(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M")


def _coerce_str(value: object, default: str = "") -> str:
    if value is None:
        return default
    if isinstance(value, str):
        return value
    return str(value)


def _coerce_float(value: object, default: float = 0.0) -> float:
    if value is None:
        return default
    if isinstance(value, (int, float)):
        return float(value)
    try:
        return float(str(value))
    except (TypeError, ValueError):
        return default


def _parse_pipeline_data(raw: object) -> list[PipelineRow]:
    if not isinstance(raw, list):
        return []

    rows: list[PipelineRow] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        row: PipelineRow = {}
        if "deal_name" in item:
            row["deal_name"] = _coerce_str(item.get("deal_name"))
        if "value" in item:
            row["value"] = _coerce_float(item.get("value"))
        if "stage" in item:
            row["stage"] = _coerce_str(item.get("stage"))
        if "close_date" in item:
            row["close_date"] = _coerce_str(item.get("close_date"))
        if "customer" in item:
            row["customer"] = _coerce_str(item.get("customer"))
        rows.append(row)
    return rows


def _parse_research_data(raw: object) -> ResearchData:
    if not isinstance(raw, dict):
        return {}

    data: ResearchData = {}
    if "company_name" in raw:
        data["company_name"] = _coerce_str(raw.get("company_name"))
    if "summary" in raw:
        data["summary"] = _coerce_str(raw.get("summary"))

    raw_articles = raw.get("articles")
    if isinstance(raw_articles, list):
        articles: list[ResearchArticle] = []
        for item in raw_articles:
            if not isinstance(item, dict):
                continue
            article: ResearchArticle = {}
            if "title" in item:
                article["title"] = _coerce_str(item.get("title"))
            if "source" in item:
                article["source"] = _coerce_str(item.get("source"))
            if "url" in item:
                article["url"] = _coerce_str(item.get("url"))
            if "date" in item:
                article["date"] = _coerce_str(item.get("date"))
            summary = item.get("summary", item.get("snippet"))
            if summary is not None:
                article["summary"] = _coerce_str(summary)
                article["snippet"] = _coerce_str(summary)
            articles.append(article)
        data["articles"] = articles

    return data


def _parse_sharepoint_docs(raw: object) -> list[SharePointDoc]:
    if not isinstance(raw, list):
        return []

    docs: list[SharePointDoc] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        doc: SharePointDoc = {}
        if "name" in item:
            doc["name"] = _coerce_str(item.get("name"))
        if "url" in item:
            doc["url"] = _coerce_str(item.get("url"))
        if "excerpt" in item:
            doc["excerpt"] = _coerce_str(item.get("excerpt"))
        docs.append(doc)
    return docs


def _parse_forecast_data(raw: object, customer_name: str) -> ForecastData | None:
    if not isinstance(raw, dict):
        return None

    items: list[ForecastItem] = []
    raw_items = raw.get("items")
    if isinstance(raw_items, list):
        for item in raw_items:
            if not isinstance(item, dict):
                continue
            items.append(
                ForecastItem(
                    category=_coerce_str(item.get("category")),
                    current_fy_revenue=_coerce_float(item.get("current_fy_revenue")),
                    growth_rate=_coerce_float(item.get("growth_rate")),
                    projected_fy_revenue=_coerce_float(item.get("projected_fy_revenue")),
                )
            )

    return ForecastData(
        customer_name=_coerce_str(raw.get("customer_name"), customer_name) or customer_name,
        current_fy_total=_coerce_float(raw.get("current_fy_total")),
        projected_fy_total=_coerce_float(raw.get("projected_fy_total")),
        overall_growth_rate=_coerce_float(raw.get("overall_growth_rate")),
        methodology=_coerce_str(raw.get("methodology")),
        items=items,
    )


def _build_report_data(arguments: dict[str, Any]) -> ReportData:
    """Construct a typed ReportData payload from loosely typed tool arguments."""
    title = _coerce_str(arguments.get("title"), "Sales Report") or "Sales Report"
    customer_name = _coerce_str(arguments.get("customer_name"), "Unknown") or "Unknown"
    pipeline_raw = arguments.get("pipeline_data", arguments.get("sections", []))
    context_value = arguments.get("additional_context")

    return ReportData(
        title=title,
        customer_name=customer_name,
        generated_at=datetime.now(),
        pipeline_data=_parse_pipeline_data(pipeline_raw),
        research_data=_parse_research_data(arguments.get("research_data", {})),
        sharepoint_docs=_parse_sharepoint_docs(arguments.get("sharepoint_docs", [])),
        additional_context=None if context_value in (None, "") else _coerce_str(context_value),
        forecast_data=_parse_forecast_data(arguments.get("forecast_data"), customer_name),
    )


def _add_doc_page_break(document: Any) -> None:
    """Call python-docx's untyped page break helper from typed code."""
    document.add_page_break()


def _build_citations(data: ReportData) -> list[str]:
    """Collect every citable source from *data* into a flat list of strings."""
    citations: list[str] = []

    citations.append(f"Fabric pipeline query — {_fmt_timestamp(data.generated_at)}")

    for article in data.research_data.get("articles", []):
        url = article.get("url", "")
        source = article.get("source", "Unknown")
        title = article.get("title", "Untitled")
        entry = f"{title} — {source}"
        if url:
            entry += f" ({url})"
        citations.append(entry)

    for doc in data.sharepoint_docs:
        name = doc.get("name", "Untitled")
        url = doc.get("url", "")
        entry = f"SharePoint: {name}"
        if url:
            entry += f" ({url})"
        citations.append(entry)

    return citations


def _load_template(template_name: str) -> str:
    """Return the raw text of a markdown template, or empty string if missing."""
    path = _TEMPLATES_DIR / template_name
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def _generate_forecast_chart(forecast: ForecastData) -> BytesIO:
    """Generate a bar chart comparing current vs projected FY revenue by category."""
    categories = [item.category for item in forecast.items]
    current = [item.current_fy_revenue / 1000 for item in forecast.items]
    projected = [item.projected_fy_revenue / 1000 for item in forecast.items]

    fig, ax = plt.subplots(figsize=(8, 4))
    x = range(len(categories))
    width = 0.35

    ax.bar([index - width / 2 for index in x], current, width, label="Current FY", color="#0078D4")
    ax.bar([index + width / 2 for index in x], projected, width, label="Projected FY", color="#50E6FF")

    ax.set_ylabel("Revenue ($K)")
    ax.set_title(f"FY Quota Forecast — {forecast.customer_name}")
    ax.set_xticks(list(x))
    ax.set_xticklabels(categories, rotation=30, ha="right", fontsize=9)
    ax.legend()
    ax.yaxis.set_major_formatter(FuncFormatter(lambda value, _: f"${value:,.0f}K"))

    fig.tight_layout()

    buffer = BytesIO()
    fig.savefig(buffer, format="png", dpi=150, bbox_inches="tight")
    plt.close(fig)
    buffer.seek(0)
    return buffer


# ---------------------------------------------------------------------------
# DOCX generation
# ---------------------------------------------------------------------------


def generate_docx(
    data: ReportData,
    template_name: str | Path,
    output_path: str | Path | None = None,
) -> str:
    """Create a Word document from *data* and return the resolved output path.

    Parameters
    ----------
    data:
        The structured report payload.
    template_name:
        Name of the markdown template, or the output path when ``output_path`` is omitted.
    output_path:
        Destination file path for the ``.docx`` file.
    """
    if output_path is None:
        output_path = template_name
        template_name = _DEFAULT_DOCX_TEMPLATE

    _ = _load_template(str(template_name))  # reserved for future template-driven rendering

    doc = Document()
    style = doc.styles["Normal"]
    style.font.size = Pt(11)
    style.font.name = "Calibri"

    # -- Title page ----------------------------------------------------------
    title_para = doc.add_heading(data.title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"Prepared for {data.customer_name}")
    run.font.size = Pt(14)

    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_para.add_run(_fmt_timestamp(data.generated_at)).font.size = Pt(12)

    _add_doc_page_break(doc)

    # -- Pipeline Overview ---------------------------------------------------
    doc.add_heading("Pipeline Overview", level=1)

    if data.pipeline_data:
        columns = ["Deal", "Value", "Stage", "Close Date"]
        table = doc.add_table(rows=1, cols=len(columns))
        table.style = "Light Shading Accent 1"
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        for idx, col_name in enumerate(columns):
            table.rows[0].cells[idx].text = col_name

        for deal in data.pipeline_data:
            row = table.add_row()
            row.cells[0].text = str(deal.get("deal_name", ""))
            row.cells[1].text = f"${deal.get('value', 0):,.0f}"
            row.cells[2].text = str(deal.get("stage", ""))
            row.cells[3].text = str(deal.get("close_date", ""))
    else:
        doc.add_paragraph("No pipeline data available.")

    # -- Customer Intelligence -----------------------------------------------
    doc.add_heading("Customer Intelligence", level=1)

    summary = data.research_data.get("summary", "")
    company = data.research_data.get("company_name", data.customer_name)
    if summary:
        doc.add_paragraph(summary)
    elif company:
        doc.add_paragraph(f"Intelligence gathered for {company}.")

    articles = data.research_data.get("articles", [])
    if articles:
        doc.add_heading("Recent News", level=2)
        for article in articles:
            title = article.get("title", "Untitled")
            source = article.get("source", "")
            date = article.get("date", "")
            article_summary = article.get("summary") or article.get("snippet", "")
            url = article.get("url", "")
            bullet_text = f"{title}"
            if source:
                bullet_text += f" — {source}"
            if date:
                bullet_text += f" ({date})"
            if url:
                bullet_text += f"\n{url}"
            if article_summary:
                bullet_text += f"\n{article_summary}"
            doc.add_paragraph(bullet_text, style="List Bullet")

    # -- Internal Context ----------------------------------------------------
    doc.add_heading("Internal Context", level=1)

    if data.sharepoint_docs:
        for sp_doc in data.sharepoint_docs:
            name = sp_doc.get("name", "Untitled")
            url = sp_doc.get("url", "")
            excerpt = sp_doc.get("excerpt", "")
            heading_text = name
            if url:
                heading_text += f" — {url}"
            doc.add_heading(heading_text, level=2)
            if excerpt:
                doc.add_paragraph(excerpt)
    else:
        doc.add_paragraph("No SharePoint documents referenced.")

    if data.additional_context:
        doc.add_heading("Additional Context", level=2)
        doc.add_paragraph(data.additional_context)

    # -- FY Quota Forecast ---------------------------------------------------
    if data.forecast_data:
        forecast = data.forecast_data
        doc.add_heading("FY Quota Forecast", level=1)

        growth_pct = f"{forecast.overall_growth_rate * 100:.1f}%"
        doc.add_paragraph(
            f"Projected revenue for {forecast.customer_name}: "
            f"${forecast.projected_fy_total:,.0f} "
            f"({growth_pct} growth from ${forecast.current_fy_total:,.0f} current FY)."
        )

        chart_buffer = _generate_forecast_chart(forecast)
        doc.add_picture(chart_buffer, width=Inches(6))
        doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER

        table = doc.add_table(rows=1, cols=4, style="Light Grid Accent 1")
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        headers = ["Product Category", "Current FY", "Growth %", "Projected FY"]
        for index, header in enumerate(headers):
            table.rows[0].cells[index].text = header

        for item in forecast.items:
            row = table.add_row()
            row.cells[0].text = item.category
            row.cells[1].text = f"${item.current_fy_revenue:,.0f}"
            row.cells[2].text = f"{item.growth_rate * 100:.1f}%"
            row.cells[3].text = f"${item.projected_fy_revenue:,.0f}"

        total_row = table.add_row()
        total_row.cells[0].text = "Total"
        total_row.cells[1].text = f"${forecast.current_fy_total:,.0f}"
        total_row.cells[2].text = growth_pct
        total_row.cells[3].text = f"${forecast.projected_fy_total:,.0f}"
        for cell in total_row.cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.bold = True

        doc.add_paragraph(f"Methodology: {forecast.methodology}", style="Intense Quote")

    # -- Sources & Citations -------------------------------------------------
    _add_doc_page_break(doc)
    doc.add_heading("Sources & Citations", level=1)

    for citation in _build_citations(data):
        doc.add_paragraph(citation, style="List Number")

    # -- Footer --------------------------------------------------------------
    footer_text = f"{_FOOTER_TEXT} — {_fmt_timestamp(data.generated_at)}"
    for section in doc.sections:
        footer = section.footer
        footer.is_linked_to_previous = False
        footer_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        footer_para.text = footer_text
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in footer_para.runs:
            run.font.size = Pt(8)

    resolved = str(Path(output_path).resolve())
    doc.save(resolved)
    return resolved


# ---------------------------------------------------------------------------
# PPTX generation
# ---------------------------------------------------------------------------


def generate_pptx(data: ReportData, template_name: str | Path, output_path: str | Path) -> str:
    """Create a PowerPoint deck from *data* and return the resolved output path.

    Parameters
    ----------
    data:
        The structured report payload.
    template_name:
        Name of the markdown template (reserved for future use).
    output_path:
        Destination file path for the ``.pptx`` file.
    """
    _ = _load_template(str(template_name))

    prs = Presentation()
    slide_width = PptxInches(13.333)
    slide_height = PptxInches(7.5)
    prs.slide_width = slide_width
    prs.slide_height = slide_height

    footer_stamp = f"{_FOOTER_TEXT} — {_fmt_timestamp(data.generated_at)}"

    def _add_footer(slide: Slide) -> None:
        """python-pptx lacks precise stubs here; use the concrete Slide type for footer placement."""
        txbox = slide.shapes.add_textbox(
            Emu(0),
            Emu(slide_height - PptxInches(0.4)),
            slide_width,
            PptxInches(0.4),
        )
        tf = txbox.text_frame
        tf.text = footer_stamp
        for para in tf.paragraphs:
            para.font.size = PptxPt(8)
            para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # -- Slide 1: Title ------------------------------------------------------
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = data.title
    slide.placeholders[1].text = f"Prepared for {data.customer_name}\n{_fmt_timestamp(data.generated_at)}"
    _add_footer(slide)

    # -- Slide 2: Pipeline ---------------------------------------------------
    blank_layout = prs.slide_layouts[5]  # blank
    slide = prs.slides.add_slide(blank_layout)
    # heading
    txbox = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(0.3), PptxInches(12), PptxInches(0.6))
    txbox.text_frame.text = "Pipeline Overview"
    txbox.text_frame.paragraphs[0].font.size = PptxPt(28)
    txbox.text_frame.paragraphs[0].font.bold = True

    if data.pipeline_data:
        rows = len(data.pipeline_data) + 1
        cols = 4
        table_shape = slide.shapes.add_table(
            rows, cols, PptxInches(0.5), PptxInches(1.2), PptxInches(12), PptxInches(4)
        )
        table = table_shape.table
        headers = ["Deal", "Value", "Stage", "Close Date"]
        for ci, h in enumerate(headers):
            table.cell(0, ci).text = h
        for ri, deal in enumerate(data.pipeline_data, start=1):
            table.cell(ri, 0).text = str(deal.get("deal_name", ""))
            table.cell(ri, 1).text = f"${deal.get('value', 0):,.0f}"
            table.cell(ri, 2).text = str(deal.get("stage", ""))
            table.cell(ri, 3).text = str(deal.get("close_date", ""))
    else:
        txbox2 = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(1.5), PptxInches(12), PptxInches(1))
        txbox2.text_frame.text = "No pipeline data available."

    _add_footer(slide)

    # -- Slide 3: Intelligence -----------------------------------------------
    slide = prs.slides.add_slide(blank_layout)
    txbox = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(0.3), PptxInches(12), PptxInches(0.6))
    txbox.text_frame.text = "Customer Intelligence"
    txbox.text_frame.paragraphs[0].font.size = PptxPt(28)
    txbox.text_frame.paragraphs[0].font.bold = True

    body_box = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(1.2), PptxInches(12), PptxInches(5.5))
    tf = body_box.text_frame
    tf.word_wrap = True

    summary = data.research_data.get("summary", "")
    company = data.research_data.get("company_name", data.customer_name)
    if summary:
        tf.text = summary
    elif company:
        tf.text = f"Intelligence gathered for {company}."

    for article in data.research_data.get("articles", []):
        p = tf.add_paragraph()
        title = article.get("title", "Untitled")
        source = article.get("source", "")
        bullet = f"• {title}"
        if source:
            bullet += f" — {source}"
        p.text = bullet
        p.font.size = PptxPt(14)

    _add_footer(slide)

    # -- Slide 4: Sources & Citations ----------------------------------------
    slide = prs.slides.add_slide(blank_layout)
    txbox = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(0.3), PptxInches(12), PptxInches(0.6))
    txbox.text_frame.text = "Sources & Citations"
    txbox.text_frame.paragraphs[0].font.size = PptxPt(28)
    txbox.text_frame.paragraphs[0].font.bold = True

    cite_box = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(1.2), PptxInches(12), PptxInches(5.5))
    cite_tf = cite_box.text_frame
    cite_tf.word_wrap = True

    citations = _build_citations(data)
    if citations:
        cite_tf.text = citations[0]
        for c in citations[1:]:
            p = cite_tf.add_paragraph()
            p.text = c
            p.font.size = PptxPt(12)
    else:
        cite_tf.text = "No sources to cite."

    _add_footer(slide)

    resolved = str(Path(output_path).resolve())
    prs.save(resolved)
    return resolved
