"""Unit tests for the Report Generator (DOCX and PPTX output)."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from docx import Document
from docx.opc.constants import RELATIONSHIP_TYPE as RT
from pptx import Presentation

from src.agents.report_generator.generator import ReportData, generate_docx, generate_pptx

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

SAMPLE_SP_DOCS: list[dict] = [
    {
        "name": "FY25 Account Strategy",
        "url": "https://contoso.sharepoint.com/sites/sales/fy25-strategy.docx",
        "excerpt": "Focus on expanding cloud adoption across APAC region with targeted workshops.",
    },
    {
        "name": "Technical Architecture Review",
        "url": "https://contoso.sharepoint.com/sites/eng/arch-review.pptx",
        "excerpt": "Current infrastructure supports 10K concurrent users; scale target is 50K.",
    },
]


def _make_report_data(
    pipeline_data: list[dict],
    research_data: dict,
    sharepoint_docs: list[dict] | None = None,
    additional_context: str | None = None,
) -> ReportData:
    return ReportData(
        title="Account Plan — Contoso Ltd",
        customer_name="Contoso Ltd",
        generated_at=datetime(2025, 7, 15, 10, 30),
        pipeline_data=pipeline_data,
        research_data=research_data,
        sharepoint_docs=sharepoint_docs or [],
        additional_context=additional_context,
    )


# ---------------------------------------------------------------------------
# DOCX tests
# ---------------------------------------------------------------------------


class TestGenerateDocx:
    """Tests for generate_docx."""

    def test_output_file_exists(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data, SAMPLE_SP_DOCS)
        out = tmp_path / "report.docx"
        result = generate_docx(data, "account_plan.md", str(out))
        assert Path(result).exists()

    def test_has_expected_sections(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data, SAMPLE_SP_DOCS)
        out = tmp_path / "report.docx"
        generate_docx(data, "account_plan.md", str(out))

        doc = Document(str(out))
        headings = [p.text for p in doc.paragraphs if p.style.name.startswith("Heading")]
        assert "Pipeline Overview" in headings
        assert "Customer Intelligence" in headings
        assert "Internal Context" in headings
        assert "Sources & Citations" in headings

    def test_pipeline_table_rows(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data)
        out = tmp_path / "report.docx"
        generate_docx(data, "account_plan.md", str(out))

        doc = Document(str(out))
        tables = doc.tables
        assert len(tables) >= 1
        # header row + 3 data rows
        assert len(tables[0].rows) == 4

    def test_citations_included(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data, SAMPLE_SP_DOCS)
        out = tmp_path / "report.docx"
        generate_docx(data, "account_plan.md", str(out))

        doc = Document(str(out))
        full_text = "\n".join(p.text for p in doc.paragraphs)
        assert "Fabric pipeline query" in full_text
        assert "Contoso Reports Record Q2 Earnings" in full_text
        assert "SharePoint: FY25 Account Strategy" in full_text

    def test_footer_present(self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data)
        out = tmp_path / "report.docx"
        generate_docx(data, "account_plan.md", str(out))

        doc = Document(str(out))
        for section in doc.sections:
            footer_text = "\n".join(p.text for p in section.footer.paragraphs)
            assert "Generated by Fabric Sales Agent Accelerator" in footer_text

    def test_minimal_data(self, tmp_path: Path) -> None:
        """Empty articles, no SP docs, no additional context."""
        data = _make_report_data(
            pipeline_data=[],
            research_data={"company_name": "Minimal Corp", "articles": []},
        )
        out = tmp_path / "minimal.docx"
        result = generate_docx(data, "account_plan.md", str(out))
        assert Path(result).exists()

        doc = Document(str(out))
        full_text = "\n".join(p.text for p in doc.paragraphs)
        assert "No pipeline data available." in full_text
        assert "No SharePoint documents referenced." in full_text

    def test_additional_context_section(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data, additional_context="Custom note here.")
        out = tmp_path / "report.docx"
        generate_docx(data, "account_plan.md", str(out))

        doc = Document(str(out))
        full_text = "\n".join(p.text for p in doc.paragraphs)
        assert "Custom note here." in full_text

    def test_docx_with_forecast_section(self, tmp_path: Path) -> None:
        """DOCX includes forecast table and chart when forecast_data is provided."""
        from src.agents.report_generator.generator import ForecastData, ForecastItem

        forecast = ForecastData(
            customer_name="Tailspin Toys",
            current_fy_total=1_250_000,
            projected_fy_total=1_400_000,
            overall_growth_rate=0.12,
            methodology="Trailing 12-month trend",
            items=[
                ForecastItem("Novelty Items", 450000, 0.12, 504000),
                ForecastItem("Clothing", 320000, 0.12, 358400),
                ForecastItem("Toys", 200000, 0.15, 230000),
            ],
        )

        data = _make_report_data([], {})
        data.forecast_data = forecast

        out = tmp_path / "forecast_report.docx"
        generate_docx(data, "account_plan.md", str(out))

        assert out.exists()
        doc = Document(str(out))

        headings = [p.text for p in doc.paragraphs if p.style.name.startswith("Heading")]
        assert "FY Quota Forecast" in headings

        assert len(doc.tables) >= 1
        forecast_table = doc.tables[-1]
        assert "Novelty Items" in forecast_table.rows[1].cells[0].text

        image_relationships = [rel for rel in doc.part.rels.values() if rel.reltype == RT.IMAGE]
        assert image_relationships, "Expected at least one embedded chart image"

    def test_docx_without_forecast(self, tmp_path: Path) -> None:
        """DOCX still generates correctly without forecast_data."""
        data = _make_report_data(
            [{"deal_name": "Test Deal", "value": 100000, "stage": "Qualify", "close_date": "2026-08-01"}],
            {"summary": "Test research", "articles": []},
        )

        out = tmp_path / "no_forecast.docx"
        generate_docx(data, "account_plan.md", str(out))
        assert out.exists()

        doc = Document(str(out))
        headings = [p.text for p in doc.paragraphs if p.style.name.startswith("Heading")]
        assert "FY Quota Forecast" not in headings


# ---------------------------------------------------------------------------
# PPTX tests
# ---------------------------------------------------------------------------


class TestGeneratePptx:
    """Tests for generate_pptx."""

    def test_output_file_exists(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data, SAMPLE_SP_DOCS)
        out = tmp_path / "deck.pptx"
        result = generate_pptx(data, "qbr_deck.md", str(out))
        assert Path(result).exists()

    def test_has_expected_slides(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data, SAMPLE_SP_DOCS)
        out = tmp_path / "deck.pptx"
        generate_pptx(data, "qbr_deck.md", str(out))

        prs = Presentation(str(out))
        assert len(prs.slides) == 4

    def test_title_slide_content(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data)
        out = tmp_path / "deck.pptx"
        generate_pptx(data, "qbr_deck.md", str(out))

        prs = Presentation(str(out))
        title_slide = prs.slides[0]
        assert title_slide.shapes.title.text == "Account Plan — Contoso Ltd"

    def test_pipeline_slide_has_table(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data)
        out = tmp_path / "deck.pptx"
        generate_pptx(data, "qbr_deck.md", str(out))

        prs = Presentation(str(out))
        pipeline_slide = prs.slides[1]
        tables = [s for s in pipeline_slide.shapes if s.has_table]
        assert len(tables) == 1
        assert len(tables[0].table.rows) == 4  # header + 3 deals

    def test_citations_slide(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data, SAMPLE_SP_DOCS)
        out = tmp_path / "deck.pptx"
        generate_pptx(data, "qbr_deck.md", str(out))

        prs = Presentation(str(out))
        citations_slide = prs.slides[3]
        all_text = " ".join(shape.text_frame.text for shape in citations_slide.shapes if shape.has_text_frame)
        assert "Fabric pipeline query" in all_text
        assert "SharePoint: FY25 Account Strategy" in all_text

    def test_footer_on_all_slides(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data)
        out = tmp_path / "deck.pptx"
        generate_pptx(data, "qbr_deck.md", str(out))

        prs = Presentation(str(out))
        for slide in prs.slides:
            all_text = " ".join(shape.text_frame.text for shape in slide.shapes if shape.has_text_frame)
            assert "Generated by Fabric Sales Agent Accelerator" in all_text

    def test_minimal_data(self, tmp_path: Path) -> None:
        """Empty pipeline, empty articles, no SP docs."""
        data = _make_report_data(
            pipeline_data=[],
            research_data={"company_name": "Minimal Corp", "articles": []},
        )
        out = tmp_path / "minimal.pptx"
        result = generate_pptx(data, "qbr_deck.md", str(out))
        assert Path(result).exists()

        prs = Presentation(str(out))
        assert len(prs.slides) == 4

    def test_intelligence_slide_bullets(
        self, tmp_path: Path, sample_pipeline_data: list[dict], sample_research_data: dict
    ) -> None:
        data = _make_report_data(sample_pipeline_data, sample_research_data)
        out = tmp_path / "deck.pptx"
        generate_pptx(data, "qbr_deck.md", str(out))

        prs = Presentation(str(out))
        intel_slide = prs.slides[2]
        all_text = " ".join(shape.text_frame.text for shape in intel_slide.shapes if shape.has_text_frame)
        assert "Contoso Reports Record Q2 Earnings" in all_text
        assert "Contoso Expands APAC Operations" in all_text
